namespace DaceasyMigration.Models
{
    public class DaceasyVendor
    {
       public string CVNo { get; set; }
       public string TaxNo { get; set; }
       public string TermNo { get; set; }
       public string MsgNo { get; set; }
       public string DefAcctNo { get; set; }
       public string GLDept { get; set; }
       public string SPNo { get; set; }
       public string Territory { get; set; }
       public string VendType { get; set; }
       public string BillGrp { get; set; }
       public string TaxId { get; set; }
       public string NoteFile { get; set; }
       public string PrBrk { get; set; }
       public string AcctType { get; set; }
       public string Taxable { get; set; }
       public string ContLabor { get; set; }
       public string CVType { get; set; }
       public string FinChg { get; set; }
       public string LastPurDate { get; set; }
       public string LastPayDate { get; set; }
       public string CrLimit { get; set; }
       public string BegBal { get; set; }
       public string CurrDr { get; set; }
       public string CurrCr { get; set; }
       public string CurrBal { get; set; }
       public string LastPurAmt { get; set; }
       public string LastPayAmt { get; set; }
       public string InvQtyYBL { get; set; }
       public string InvQtyLY { get; set; }
       public string InvQtyYTD { get; set; }
       public string InvQtyBUD { get; set; }
       public string InvQtyNY { get; set; }
       public string RetQtyYBL { get; set; }
       public string RetQtyLY { get; set; }
       public string RetQtyYTD { get; set; }
       public string RetQtyBUD { get; set; }
       public string RetQtyNY { get; set; }
       public string PurAmtYBL { get; set; }
       public string PurAmtLY { get; set; }
       public string PurAmtYTD { get; set; }
       public string PurAmtBUD { get; set; }
       public string PurAmtNY { get; set; }
       public string CostAmtYBL { get; set; }
       public string CostAmtLY { get; set; }
       public string CostAmtYTD { get; set; }
       public string CostAmtBUD { get; set; }
       public string CostAmtNY { get; set; }
       public string PayAmtYBL { get; set; }
       public string PayAmtLY { get; set; }
       public string PayAmtYTD { get; set; }
       public string PayAmtBUD { get; set; }
       public string PayAmtNY { get; set; }
       public string Name { get; set; }
       public string Contact { get; set; }
       public string Add1 { get; set; }
       public string Add2 { get; set; }
       public string Add3 { get; set; }
       public string City { get; set; }
       public string State { get; set; }
       public string Zip { get; set; }
       public string Phone1 { get; set; }
       public string Phone2 { get; set; }
       public string Fax { get; set; }
       public string eMAIL { get; set; }
       public string Country { get; set; }
       public string Zone { get; set; }
       public string ArApAcct { get; set; }
       public string ShipVia { get; set; }
       public string Status { get; set; }
       public string SuspenseAcct { get; set; }
       public string Memo { get; set; }
       public string MinFinCharge { get; set; } 
    }
}