namespace DaceasyMigration
{
    public class DaceasyCustomer
    {
       public string CvNo { get; set; }
       public string TaxNo { get; set; }
       public string TermNo { get; set; }
       public string MsgNo { get; set; }
       public string DefAcctNo { get; set; }
       public string GlDept { get; set; }
       public string SpNo { get; set; }
       public string Territory { get; set; }
       public string VendType { get; set; }
       public string BillGrp { get; set; }
       public string TaxId { get; set; }
       public string NoteFile { get; set; }
       public string PrBrk { get; set; }
       public string AcctType { get; set; }
       public string Taxable { get; set; }
       public string ContLabor { get; set; }
       public string CvType { get; set; }
       public string FinChg { get; set; }
       public string LastPurDate { get; set; }
       public string LastPayDate { get; set; }
       public string CrLimit { get; set; }
       public string BegBal { get; set; }
       public string CurrDr { get; set; }
       public string CurrCr { get; set; }
       public string CurrBal { get; set; }
       public string LastPurAmt { get; set; }
       public string LastPayAmt { get; set; }
       public string InvQtyYbl { get; set; }
       public string InvQtyLy { get; set; }
       public string InvQtyYtd { get; set; }
       public string InvQtyBud { get; set; }
       public string InvQtyNy { get; set; }
       public string RetQtyYbl { get; set; }
       public string RetQtyLy { get; set; }
       public string RetQtyYtd { get; set; }
       public string RetQtyBud { get; set; }
       public string RetQtyNy { get; set; }
       public string PurAmtYbl { get; set; }
       public string PurAmtLy { get; set; }
       public string PurAmtYtd { get; set; }
       public string PurAmtBud { get; set; }
       public string PurAmtNy { get; set; }
       public string CostAmtYbl { get; set; }
       public string CostAmtLy { get; set; }
       public string CostAmtYtd { get; set; }
       public string CostAmtBud { get; set; }
       public string CostAmtNy { get; set; }
       public string PayAmtYbl { get; set; }
       public string PayAmtLy { get; set; }
       public string PayAmtYtd { get; set; }
       public string PayAmtBud { get; set; }
       public string PayAmtNy { get; set; }
       public string Name { get; set; }
       public string Contact { get; set; }
       public string Add1 { get; set; }
       public string Add2 { get; set; }
       public string Add3 { get; set; }
       public string City { get; set; }
       public string State { get; set; }
       public string Zip { get; set; }
       public string Phone1 { get; set; }
       public string Phone2 { get; set; }
       public string Fax { get; set; }
       public string EMail { get; set; }
       public string Country { get; set; }
       public string Zone { get; set; }
       public string ArApAcct { get; set; }
       public string ShipVia { get; set; }
       public string Status { get; set; }
       public string SuspenseAcct { get; set; }
       public string Memo { get; set; }
       public string MinFinCharge { get; set; } 
    }
}